import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F5F7FB',
    },
    scrollContent: {
        paddingHorizontal: 22,
        paddingTop: 22,
        paddingBottom: 36,
        gap: 16,
    },
    heroWrap: {
        alignItems: 'center',
        paddingTop: 8,
        paddingBottom: 8,
    },
    title: {
        color: '#1B2B4A',
        fontSize: 40,
        fontWeight: '800',
        letterSpacing: -0.6,
        marginTop: 12,
    },
    subtitle: {
        color: '#536A90',
        marginTop: 4,
        fontSize: 14,
        letterSpacing: 2,
        fontWeight: '700',
    },
    musicIconWrap: {
        width: 68,
        height: 68,
        borderRadius: 18,
        backgroundColor: '#5A57E8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E0E6F2',
        padding: 16,
    },
    cardHeadRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    cardHeadLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    cardIconPill: {
        width: 38,
        height: 38,
        borderRadius: 12,
        backgroundColor: '#FFF7E0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardIconPillAlt: {
        width: 38,
        height: 38,
        borderRadius: 12,
        backgroundColor: '#E9EDFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardIconPillRed: {
        width: 38,
        height: 38,
        borderRadius: 12,
        backgroundColor: '#FFECEF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionLabel: {
        color: '#63799D',
        fontSize: 11,
        letterSpacing: 1.6,
        fontWeight: '700',
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 3,
    },
    readyDot: {
        width: 7,
        height: 7,
        borderRadius: 4,
        backgroundColor: '#3ECF63',
    },
    readyText: {
        color: '#28A652',
        fontSize: 12,
        fontWeight: '600',
    },
    changeBtn: {
        backgroundColor: '#F2F5FD',
        borderWidth: 1,
        borderColor: '#DEE6F5',
        borderRadius: 16,
        paddingHorizontal: 18,
        paddingVertical: 8,
    },
    changeBtnText: {
        color: '#5364F5',
        fontWeight: '700',
        fontSize: 14,
    },
    inputRow: {
        backgroundColor: '#F8FAFF',
        borderRadius: 16,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#E3E9F5',
    },
    inputText: {
        color: '#16315A',
        fontSize: 27,
        fontWeight: '500',
        letterSpacing: -0.5,
    },
    examinedRow: {
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    lastRunRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    lastRunLabel: {
        color: '#6D7F9C',
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.7,
    },
    examinedBadge: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E3DDFC',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 10,
        paddingVertical: 6,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
    },
    examinedText: {
        color: '#7A61F6',
        fontSize: 12,
        fontWeight: '600',
    },
    targetCard: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E0E6F2',
        borderRadius: 20,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    targetContentWrap: {
        flex: 1,
        marginRight: 12,
        gap: 8,
    },
    targetPathText: {
        color: '#28456F',
        fontSize: 14,
        fontWeight: '600',
    },
    targetPathMuted: {
        color: '#8294B2',
        fontWeight: '500',
    },
    selectBtn: {
        backgroundColor: '#4E4FF0',
        borderRadius: 0,
        paddingHorizontal: 16,
        paddingVertical: 9,
        minWidth: 104,
        alignItems: 'center',
    },
    selectBtnText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.8,
    },
    storageCard: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#F0D8D8',
        borderRadius: 20,
        padding: 16,
    },
    storageHead: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    storageSub: {
        color: '#8A98AF',
        fontSize: 12,
        marginTop: 2,
    },
    deniedPill: {
        borderRadius: 14,
        paddingHorizontal: 10,
        paddingVertical: 4,
        backgroundColor: '#FBE7E7',
        borderWidth: 1,
        borderColor: '#F7CDCD',
    },
    deniedText: {
        color: '#CE4141',
        fontSize: 12,
        fontWeight: '700',
    },
    readyPill: {
        backgroundColor: '#E8F7EC',
        borderColor: '#C7E9D0',
    },
    readyPillText: {
        color: '#2A8E4D',
    },
    alertCard: {
        borderWidth: 1,
        borderColor: '#F6E0E0',
        backgroundColor: '#FFF4F4',
        borderLeftWidth: 3,
        borderLeftColor: '#F14747',
        borderRadius: 12,
        padding: 12,
    },
    alertTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    alertTitle: {
        color: '#C92424',
        fontSize: 20,
        fontWeight: '700',
    },
    alertBody: {
        color: '#D13F3F',
        fontSize: 13,
        marginTop: 6,
        marginBottom: 8,
        lineHeight: 18,
    },
    grantText: {
        color: '#3649E7',
        fontSize: 13,
        fontWeight: '700',
        textDecorationLine: 'underline',
    },
    startBtn: {
        marginTop: 14,
        borderRadius: 18,
        height: 66,
        backgroundColor: '#4E4FF0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    startBtnDisabled: {
        backgroundColor: '#E8EDF5',
    },
    startBtnText: {
        color: '#FFFFFF',
        fontSize: 30,
        fontWeight: '700',
        letterSpacing: 1,
    },
    startBtnTextDisabled: {
        color: '#9AACCA',
    },
    sourceModeText: {
        textAlign: 'center',
        color: '#8294B2',
        fontSize: 12,
        marginTop: 2,
    },
});

export default styles;
