import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F5F7FB',
    },
    page: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 16,
    },
    topRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
    },
    title: {
        color: '#162B4C',
        fontSize: 30,
        fontWeight: '800',
        letterSpacing: -0.4,
    },
    subtitle: {
        color: '#6C7E9E',
        marginTop: 2,
        fontSize: 13,
    },
    percent: {
        color: '#4E4FF0',
        fontSize: 32,
        fontWeight: '700',
    },
    progressTrack: {
        marginTop: 14,
        height: 8,
        borderRadius: 8,
        backgroundColor: '#D6DEEC',
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#19D1BA',
    },
    progressMetaRow: {
        marginTop: 9,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    metaLeft: {
        color: '#6C7E9E',
        fontSize: 12,
    },
    metaRight: {
        color: '#DF3F3F',
        fontSize: 12,
        fontWeight: '700',
    },
    sectionHeaderError: {
        marginTop: 10,
        paddingVertical: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: '#E9EDF5',
    },
    sectionHeader: {
        marginTop: 10,
        paddingVertical: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: '#E9EDF5',
    },
    sectionTitleWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 7,
    },
    sectionTitle: {
        color: '#51698F',
        fontSize: 12,
        letterSpacing: 1.5,
        fontWeight: '700',
    },
    sectionTitleError: {
        color: '#D64646',
        fontSize: 12,
        letterSpacing: 1.5,
        fontWeight: '700',
    },
    sectionCountPill: {
        backgroundColor: '#1D212A',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#2D3340',
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    sectionCountText: {
        color: '#6E7895',
        fontSize: 10,
        fontWeight: '700',
    },
    listBox: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#DDE5F2',
        backgroundColor: '#FFFFFF',
        height: 188,
        overflow: 'hidden',
    },
    listBoxError: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#F2D3D3',
        backgroundColor: '#FFF3F3',
        height: 172,
        overflow: 'hidden',
    },
    listBoxCleanup: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E5EAF4',
        backgroundColor: '#F7F9FD',
        height: 120,
        overflow: 'hidden',
    },
    listScroll: {
        padding: 8,
    },
    fileCard: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#DEE6F4',
        backgroundColor: '#FFFFFF',
        padding: 10,
        marginBottom: 8,
    },
    fileCardError: {
        borderColor: '#F3B3B3',
        backgroundColor: '#FFF7F7',
    },
    fileCardCleanup: {
        borderColor: '#E2E7F1',
        backgroundColor: '#F7F9FD',
    },
    fileCardMulti: {
        borderColor: '#A4A8FF',
        backgroundColor: '#F4F5FF',
    },
    fileTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
        gap: 8,
    },
    titleLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 8,
        flex: 1,
    },
    fileName: {
        color: '#162B4C',
        fontSize: 14,
        fontWeight: '600',
        flexShrink: 1,
    },
    fileNameMuted: {
        color: '#8A97AE',
        fontSize: 14,
        fontWeight: '600',
        textDecorationLine: 'line-through',
        flexShrink: 1,
    },
    multiTargetPill: {
        backgroundColor: '#554213',
        borderRadius: 8,
        paddingHorizontal: 7,
        paddingVertical: 3,
    },
    multiTargetText: {
        color: '#FFC860',
        fontSize: 9,
        fontWeight: '700',
    },
    statusPill: {
        borderRadius: 10,
        paddingHorizontal: 8,
        paddingVertical: 4,
        minWidth: 70,
        alignItems: 'center',
    },
    statusText: {
        color: '#111315',
        fontSize: 10,
        fontWeight: '700',
    },
    statusPillError: {
        backgroundColor: '#FCE1E1',
    },
    statusTextError: {
        color: '#C84646',
        fontSize: 10,
        fontWeight: '700',
    },
    pathLabel: {
        color: '#607393',
        fontSize: 11,
    },
    pathLabelMuted: {
        color: '#98A3B8',
        fontSize: 10,
        fontWeight: '700',
    },
    pathLine: {
        color: '#415C9D',
        fontSize: 11,
        marginTop: 3,
        fontWeight: '600',
    },
    pathLineMuted: {
        color: '#B0BACB',
        fontSize: 10,
        marginTop: 3,
        fontStyle: 'italic',
    },
    reasonText: {
        color: '#C24A4A',
        fontSize: 11,
        marginBottom: 4,
    },
    emptyState: {
        color: '#7D8EA9',
        fontSize: 12,
        padding: 8,
    },
    logButton: {
        marginTop: 12,
        borderRadius: 14,
        height: 46,
        borderWidth: 1,
        borderColor: '#DFE6F4',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
    },
    logButtonText: {
        color: '#4E50E8',
        fontSize: 15,
        fontWeight: '600',
    },
    bottomButton: {
        marginTop: 12,
        borderRadius: 14,
        height: 50,
        backgroundColor: '#8C8AF0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    bottomButtonDisabled: {
        opacity: 0.6,
    },
    bottomButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    logRefText: {
        marginTop: 9,
        color: '#7F889E',
        fontSize: 10,
        textAlign: 'center',
    },
});

export default styles;
